"""
Case table: ``main.py`` mixin methods that forward to a ``self``-held collaborator.

Two shapes are covered: facades and coordinators reached through an attribute
(``self._file_series_coordinator.on_show_file_from_series(...)``) and handler
modules imported under an alias (``layout_on_swap_view_requested``). The former
additionally pin return-value propagation, because a getter that drops the
collaborator's value fails silently.
"""

from __future__ import annotations

from main_mixin_delegation_support import CollaboratorCase, HandlerCase

COLLABORATOR_CASES: tuple[CollaboratorCase, ...] = (
    CollaboratorCase(
        "DisplayProjectionMixin",
        "_on_projection_enabled_changed",
        "_projection_app_facade",
        "on_projection_enabled_changed",
        (True,),
    ),
    CollaboratorCase(
        "DisplayProjectionMixin",
        "_on_projection_type_changed",
        "_projection_app_facade",
        "on_projection_type_changed",
        ("MIP",),
    ),
    CollaboratorCase(
        "DisplayProjectionMixin",
        "_on_projection_slice_count_changed",
        "_projection_app_facade",
        "on_projection_slice_count_changed",
        (9,),
    ),
    CollaboratorCase(
        "DisplayProjectionMixin",
        "_refresh_overlays_after_privacy_change",
        "_privacy_controller",
        "refresh_overlays",
        (),
    ),
    CollaboratorCase(
        "SettingsLayoutMixin",
        "_on_series_navigator_selected",
        "_file_series_coordinator",
        "on_series_navigator_selected",
        ("1.2.3",),
    ),
    CollaboratorCase(
        "SettingsLayoutMixin",
        "_on_series_navigator_instance_selected",
        "_file_series_coordinator",
        "on_series_navigator_instance_selected",
        ("1.2", "1.2.3", 4),
    ),
    CollaboratorCase("UIHandlersMixin", "_on_series_navigation_requested", "_file_series_coordinator", "on_series_navigation_requested", (1,)),
    CollaboratorCase(
        "UIHandlersMixin",
        "_on_assign_series_from_context_menu",
        "_file_series_coordinator",
        "on_assign_series_from_context_menu",
        ("1.2.3",),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_on_show_file_from_series",
        "_file_series_coordinator",
        "on_show_file_from_series",
        ("1.2", "1.2.3"),
    ),
    CollaboratorCase("UIHandlersMixin", "_set_mouse_mode_via_handler", "mouse_mode_handler", "set_mouse_mode", ("window_level",)),
    CollaboratorCase("UIHandlersMixin", "_on_window_changed", "view_state_manager", "handle_window_changed", (40.0, 400.0)),
    CollaboratorCase("UIHandlersMixin", "_on_mouse_mode_changed", "mouse_mode_handler", "handle_mouse_mode_changed", ("pan",)),
    CollaboratorCase("UIHandlersMixin", "_set_mouse_mode", "mouse_mode_handler", "set_mouse_mode", ("roi",)),
    CollaboratorCase("UIHandlersMixin", "_on_arrow_key_pressed", "slice_display_manager", "handle_arrow_key_pressed", (-1,)),
    CollaboratorCase(
        "InitializationMixin",
        "_connect_focused_subwindow_signals",
        "_subwindow_lifecycle_controller",
        "connect_focused_subwindow_signals",
        (),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_on_context_menu_mouse_mode_changed",
        "mouse_mode_handler",
        "handle_context_menu_mouse_mode_changed",
        ("pan",),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_on_context_menu_scroll_wheel_mode_changed",
        "mouse_mode_handler",
        "handle_context_menu_scroll_wheel_mode_changed",
        ("slice",),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_handle_load_first_slice",
        "_file_series_coordinator",
        "handle_load_first_slice",
        ({"1.2": {"1.2.3": {}}},),
    ),
    CollaboratorCase("FileOperationsMixin", "_open_export", "_export_app_facade", "open_export", ()),
    CollaboratorCase(
        "FileOperationsMixin",
        "_open_deep_anonymizer_export",
        "_export_app_facade",
        "open_deep_anonymizer_export",
        (),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_open_export_screenshots",
        "_export_app_facade",
        "open_export_screenshots",
        (),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_build_flat_series_list",
        "_file_series_coordinator",
        "build_flat_series_list",
        ({"s": {}},),
        returns=[(0, "1.2", "CT", object())],
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_get_file_path_for_dataset",
        "_file_series_coordinator",
        "get_file_path_for_dataset",
        (object(), "1.2", "1.2.3", 0),
        returns="/data/a.dcm",
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_get_current_slice_file_path",
        "_file_series_coordinator",
        "get_current_slice_file_path",
        (2,),
        returns="/data/b.dcm",
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_update_about_this_file_dialog",
        "_file_series_coordinator",
        "update_about_this_file_dialog",
        (),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_on_about_this_file_from_series",
        "_file_series_coordinator",
        "on_about_this_file_from_series",
        ("1.2", "1.2.3"),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_resolve_focused_series_ordered_paths",
        "_export_app_facade",
        "resolve_focused_series_ordered_paths",
        (),
        returns=("1.2", "1.2.3", "CT", ["/data/a.dcm"], [object()]),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_on_right_mouse_press_for_drag",
        "view_state_manager",
        "handle_right_mouse_press_for_drag",
        (),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_on_window_level_drag_changed",
        "view_state_manager",
        "handle_window_level_drag",
        (5.0, -20.0),
    ),
    CollaboratorCase("TagEditingMixin", "get_tag_export_union_snapshot", "tag_export_union_host", "get_snapshot", (), returns=(3, {"a": 1})),
    CollaboratorCase("TagEditingMixin", "_drain_tag_export_union_worker", "tag_export_union_host", "drain_worker", (12.5,)),
    CollaboratorCase("TagEditingMixin", "_schedule_tag_export_union_rebuild", "tag_export_union_host", "schedule_rebuild", ()),
    CollaboratorCase("TagEditingMixin", "_update_tag_viewer", "dialog_coordinator", "update_tag_viewer", (object(),)),
    CollaboratorCase(
        "ROIWorkflowMixin",
        "_display_rois_for_subwindow",
        "_subwindow_lifecycle_controller",
        "display_rois_for_subwindow",
        (1, False),
    ),
    CollaboratorCase("ROIWorkflowMixin", "_open_export_roi_statistics", "_export_app_facade", "open_export_roi_statistics", ()),
    CollaboratorCase("ROIWorkflowMixin", "_set_roi_mode", "mouse_mode_handler", "set_roi_mode", ("ellipse",)),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_drawing_started", "roi_coordinator", "handle_roi_drawing_started", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_drawing_updated", "roi_coordinator", "handle_roi_drawing_updated", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_drawing_finished", "roi_coordinator", "handle_roi_drawing_finished", ()),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_clicked", "roi_coordinator", "handle_roi_clicked", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_image_clicked_no_roi", "roi_coordinator", "handle_image_clicked_no_roi", ()),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_selected", "roi_coordinator", "handle_roi_selected", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_delete_requested", "roi_coordinator", "handle_roi_delete_requested", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_roi_deleted", "roi_coordinator", "handle_roi_deleted", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_scene_selection_changed", "roi_coordinator", "handle_scene_selection_changed", ()),
    CollaboratorCase("ROIWorkflowMixin", "_update_roi_statistics", "roi_coordinator", "update_roi_statistics", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_measurement_started", "measurement_coordinator", "handle_measurement_started", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_measurement_updated", "measurement_coordinator", "handle_measurement_updated", (object(),)),
    CollaboratorCase("ROIWorkflowMixin", "_on_measurement_finished", "measurement_coordinator", "handle_measurement_finished", ()),
    CollaboratorCase(
        "ROIWorkflowMixin",
        "_on_measurement_delete_requested",
        "measurement_coordinator",
        "handle_measurement_delete_requested",
        (object(),),
    ),
    CollaboratorCase(
        "ROIWorkflowMixin",
        "_on_clear_measurements_requested",
        "measurement_coordinator",
        "handle_clear_measurements",
        (),
    ),
    CollaboratorCase("ROIWorkflowMixin", "_hide_measurement_labels", "measurement_coordinator", "hide_measurement_labels", (True,)),
    CollaboratorCase("ROIWorkflowMixin", "_hide_measurement_graphics", "measurement_coordinator", "hide_measurement_graphics", (False,)),
    CollaboratorCase("ROIWorkflowMixin", "_hide_roi_labels", "overlay_coordinator", "hide_roi_labels", (True,)),
    CollaboratorCase("ROIWorkflowMixin", "_hide_roi_graphics", "overlay_coordinator", "hide_roi_graphics", (False,)),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_get_subwindow_dataset",
        "_subwindow_lifecycle_controller",
        "get_subwindow_dataset",
        (2,),
        returns=object(),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_get_subwindow_slice_index",
        "_subwindow_lifecycle_controller",
        "get_subwindow_slice_index",
        (2,),
        returns=11,
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_get_subwindow_slice_display_manager",
        "_subwindow_lifecycle_controller",
        "get_subwindow_slice_display_manager",
        (1,),
        returns=object(),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_get_subwindow_study_uid",
        "_subwindow_lifecycle_controller",
        "get_subwindow_study_uid",
        (1,),
        returns="1.2",
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_get_subwindow_series_uid",
        "_subwindow_lifecycle_controller",
        "get_subwindow_series_uid",
        (1,),
        returns="1.2.3",
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "get_focused_subwindow_index",
        "_subwindow_lifecycle_controller",
        "get_focused_subwindow_index",
        (),
        returns=2,
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "get_histogram_callbacks_for_subwindow",
        "_subwindow_lifecycle_controller",
        "get_histogram_callbacks_for_subwindow",
        (0,),
        returns={"on_wl": lambda: None},
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_update_right_panel_for_focused_subwindow",
        "_subwindow_lifecycle_controller",
        "update_right_panel_for_focused_subwindow",
        (),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_update_left_panel_for_focused_subwindow",
        "_subwindow_lifecycle_controller",
        "update_left_panel_for_focused_subwindow",
        (),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_get_focused_subwindow",
        "_subwindow_lifecycle_controller",
        "get_focused_subwindow",
        (),
        returns=object(),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_assign_series_to_subwindow",
        "_subwindow_lifecycle_controller",
        "assign_series_to_subwindow",
        (object(), "1.2.3", 0),
    ),
    CollaboratorCase(
        "SubwindowManagementMixin",
        "_disconnect_focused_subwindow_signals",
        "_subwindow_lifecycle_controller",
        "disconnect_focused_subwindow_signals",
        (),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_qa_build_preflight_warnings",
        "_qa_app_facade",
        "build_preflight_warnings",
        ("CT", True, None, [], "CT"),
        returns=["no series selected"],
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_qa_user_confirms_preflight",
        "_qa_app_facade",
        "user_confirms_preflight",
        (["no series selected"],),
        returns=True,
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_show_qa_result_dialog",
        "_qa_app_facade",
        "show_qa_result_dialog",
        ("ACR CT", object()),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_export_qa_json",
        "_qa_app_facade",
        "export_qa_json",
        (object(), "acr_ct", {"a": 1}),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_qa_offer_extent_retry",
        "_qa_app_facade",
        "offer_extent_retry",
        (object(), {"a": 1}),
        {
            "progress_title": "t",
            "progress_label": "l",
            "result_dialog_title": "r",
            "json_default_stem": "s",
        },
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_start_qa_worker",
        "_qa_app_facade",
        "start_qa_worker",
        (object(),),
        {
            "progress_title": "t",
            "progress_label": "l",
            "result_dialog_title": "r",
            "json_default_stem": "s",
            "json_inputs": None,
            "allow_extent_retry": True,
        },
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_start_mri_batch_worker",
        "_qa_app_facade",
        "start_mri_batch_worker",
        (object(), object()),
        {"json_inputs": {"a": 1}},
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_note_mri_compare_dialog_closed",
        "_qa_app_facade",
        "note_mri_compare_dialog_closed",
        (7,),
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_show_mri_compare_result_dialog",
        "_qa_app_facade",
        "show_mri_compare_result_dialog",
        (object(),),
        {"json_inputs": {"a": 1}},
    ),
    CollaboratorCase(
        "UIHandlersMixin",
        "_export_mri_compare_json",
        "_qa_app_facade",
        "export_mri_compare_json",
        (object(), {"a": 1}),
    ),
    CollaboratorCase(
        "FileOperationsMixin",
        "_prompt_save_path",
        "_export_app_facade",
        "prompt_save_path",
        ("Save CSV", "out.csv", "CSV (*.csv)"),
        {"remember_pylinac_output_dir": True},
        returns="/tmp/out.csv",
    ),
    # MPRNavigationMixin
    CollaboratorCase(
        "MPRNavigationMixin",
        "_sync_intensity_projection_widget_from_mpr_data",
        "_projection_app_facade",
        "sync_intensity_projection_widget_from_mpr_data",
        ({"mpr_combine_type": "MIP"},),
    ),
    CollaboratorCase(
        "MPRNavigationMixin",
        "_on_save_mpr_as_dicom",
        "_mpr_controller",
        "prompt_save_mpr_as_dicom",
        (),
    ),
    CollaboratorCase(
        "MPRNavigationMixin",
        "_on_mpr_clear_from_navigator_thumbnail",
        "_mpr_controller",
        "clear_view",
        (7,),
    ),
)


#: SubwindowManagementMixin / MPRNavigationMixin forwards into layout + MPR helpers.
LAYOUT_HANDLER_CASES: tuple[HandlerCase, ...] = (
    # --- SubwindowManagementMixin -> manager factory / session reset / study nav ---
    HandlerCase(
        "SubwindowManagementMixin",
        "_build_managers_for_subwindow",
        "build_managers_for_subwindow",
        (1, object()),
    ),
    HandlerCase("SubwindowManagementMixin", "_clear_subwindow", "clear_subwindow", (2,)),
    HandlerCase(
        "SubwindowManagementMixin",
        "_reset_focused_subwindow_state_after_close",
        "reset_focused_subwindow_state_after_close",
        (),
    ),
    HandlerCase(
        "SubwindowManagementMixin",
        "_on_clear_subwindow_content_requested",
        "clear_subwindow_content",
        (2,),
    ),
    HandlerCase("SubwindowManagementMixin", "_close_series", "close_series", ("1.2", "1.2.3")),
    HandlerCase("SubwindowManagementMixin", "_close_study", "close_study", ("1.2",)),
    HandlerCase(
        "SubwindowManagementMixin",
        "_ensure_all_subwindows_have_managers",
        "layout_ensure_all_subwindows_have_managers",
        (),
    ),
    HandlerCase(
        "SubwindowManagementMixin",
        "_refresh_overlay_all_subwindows",
        "refresh_overlay_all_subwindows",
        (),
    ),
    HandlerCase(
        "SubwindowManagementMixin",
        "_capture_subwindow_view_states",
        "layout_capture_subwindow_view_states",
        (),
    ),
    HandlerCase(
        "SubwindowManagementMixin",
        "_restore_subwindow_views",
        "layout_restore_subwindow_views",
        ({0: {"zoom": 1.0}},),
    ),
    HandlerCase(
        "MPRNavigationMixin",
        "_get_subwindow_mpr_pixel_array",
        "mpr_thumb_get_subwindow_pixel_array",
        (1, 4),
    ),
    HandlerCase("MPRNavigationMixin", "_update_mpr_navigator_thumbnail", "mpr_thumb_refresh_pane_tile", (1,)),
    HandlerCase("MPRNavigationMixin", "_on_mpr_duplicate_requested", "show_duplicate_target_menu", (9,)),
    HandlerCase("MPRNavigationMixin", "_sync_mpr_navigator_tiles", "mpr_thumb_sync_tiles", (frozenset({4}),)),
)
